# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

#设置别名，防止重复引用
post_install do |installer_representation|
installer_representation.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited), PodsDummy_Pods=SomeOtherNamePodsDummy_Pods'
end
end
end

target 'LG-XMPPDemo' do

pod "MBProgressHUD"
pod "MJRefresh"
pod "SDWebImage"

pod "XMPPFramework"
pod "MessageDisplayKit", "~> 5.4"          #修改了 XHAudioPlayerHelper.h文件，增加代理，同时外置了XHMessageTableViewController.h的一个keyboardViewHeight属性，可搜索“add by jamie”找到修改内容
pod "XHPopMenu"
end

target 'LG-XMPPDemoTests' do

end